In [3]:
import numpy as np
import pandas as pd

# Load the CSV file
data = pd.read_csv(r"C:\Users\goura\Desktop\PythonProjects\experiment - 4\Book1.csv")

# Print the column names to understand the structure
print("Columns in CSV:", data.columns)

# Function to extract numerical values
def extract_number(text):
    try:
        # Extract the number after "-"
        return float(text.split("-")[-1].strip())
    except:
        # If the value is already numeric, return it as float
        return float(text)

# Apply the function to 'Sleep' and 'Study' columns
data['Sleep'] = data['Sleep'].apply(extract_number)
data['Study'] = data['Study'].apply(extract_number)

# Convert 'Percentage' column to float
data['Percentage'] = data['Percentage'].astype(float)

# Extract input (X) and output (y) values
X = data[['Sleep', 'Study']].values.astype(float)
y = data[['Percentage']].values.astype(float)

# Normalize input and output
X = X / X.max(axis=0)  # Normalize input
y = y / 100  # Normalize output to be between 0 and 1

print("Normalized Input Data (X):\n", X)
print("Normalized Output Data (y):\n", y)

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid
def derivatives_sigmoid(x):
    return x * (1 - x)

# Initialize variables
epoch = 5000  # Number of training iterations
lr = 0.1  # Learning rate
inputlayer_neurons = X.shape[1]  # Number of input features
hiddenlayer_neurons = 3  # Number of neurons in hidden layer
output_neurons = 1  # Number of neurons in output layer

# Weight and bias initialization
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))  # Weights for input to hidden layer
bh = np.random.uniform(size=(1, hiddenlayer_neurons))  # Bias for hidden layer
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))  # Weights for hidden to output layer
bout = np.random.uniform(size=(1, output_neurons))  # Bias for output layer

# Training the neural network
for i in range(epoch):
    # Forward propagation
    hinp = np.dot(X, wh) + bh  # Input to hidden layer
    hlayer_act = sigmoid(hinp)  # Apply activation function to get hidden layer output
    outinp = np.dot(hlayer_act, wout) + bout  # Input to output layer
    output = sigmoid(outinp)  # Apply activation function to get final output

    # Backpropagation
    E = y - output  # Error in output
    outgrad = derivatives_sigmoid(output)  # Gradient of output
    d_output = E * outgrad  # Error term for output layer

    EH = d_output.dot(wout.T)  # Error in hidden layer
    hiddengrad = derivatives_sigmoid(hlayer_act)  # Gradient of hidden layer
    d_hiddenlayer = EH * hiddengrad  # Error term for hidden layer

    # Update weights and biases using gradient descent
    wout += hlayer_act.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X.T.dot(d_hiddenlayer) * lr
    bh += np.sum(d_hiddenlayer, axis=0, keepdims=True) * lr

# Print the final output after training
print("Input Data: \n", X)
print("Actual Output:\n", y)
print("Predicted Output:\n", output)


Columns in CSV: Index(['Sleep', 'Study', 'Percentage'], dtype='object')
Normalized Input Data (X):
 [[0.66666667 0.4       ]
 [0.77777778 0.6       ]
 [0.88888889 0.8       ]
 [0.55555556 0.2       ]
 [1.         1.        ]]
Normalized Output Data (y):
 [[0.65]
 [0.75]
 [0.85]
 [0.55]
 [0.9 ]]
Input Data: 
 [[0.66666667 0.4       ]
 [0.77777778 0.6       ]
 [0.88888889 0.8       ]
 [0.55555556 0.2       ]
 [1.         1.        ]]
Actual Output:
 [[0.65]
 [0.75]
 [0.85]
 [0.55]
 [0.9 ]]
Predicted Output:
 [[0.67345101]
 [0.7527763 ]
 [0.81252055]
 [0.58088589]
 [0.85371952]]
